### ISSUE TITLE
Icon file included twice?

### ISSUE THREAD

**Issue by Kebap** [demonnic/muddler#16]
So I added an icon file to [my muddler package](https://github.com/MorgenGrauen/mg-mudlet/actions/runs/919756060), but it seems to be included twice:

Once in the main directory, then again in the icon's sub-folder. Did I do it wrong? I only put it in "resources" folder and linked it in config.lua..

**Comment by Kebap** [comment]
There seems to be no documentation about the "resources" folder at all.

How can files put in there be accessed from inside Lua scripts?

**Comment by demonnic** [comment]
You did it right, I am only copying it rather than moving it as it may also be something you want to use in your package itself. 

 src/resources/* is copied into the package root, so that is where you want to put those files (background images, fonts, etc).

This may be a thing that I didn't think to document because it was obvious to me as the person who made the decision, I'll add some documentation for it
